const WIKI_DATA = {
  survivors: [
    { name: "Dwight Fairfield", aliases: ["Dwight", "Pizza Dwight"] },
    { name: "Meg Thomas", aliases: ["Meg"] },
    { name: "Claudette Morel", aliases: ["Claudette", "Claud"] },
    { name: "Jake Park", aliases: ["Jake"] },
    { name: "Nea Karlsson", aliases: ["Nea"] },
    { name: "Laurie Strode", aliases: ["Laurie"] },
    { name: "Ace Visconti", aliases: ["Ace"] },
    { name: "Bill Overbeck", aliases: ["Bill", "William Overbeck"] },
    { name: "Feng Min", aliases: ["Feng"] },
    { name: "David King", aliases: ["David"] },
    { name: "Quentin Smith", aliases: ["Quentin"] },
    { name: "David Tapp", aliases: ["Tapp", "Detective Tapp"] },
    { name: "Kate Denson", aliases: ["Kate"] },
    { name: "Adam Francis", aliases: ["Adam"] },
    { name: "Jeff Johansen", aliases: ["Jeff", "Jeffrey Johansen"] },
    { name: "Jane Romero", aliases: ["Jane"] },
    { name: "Ash Williams", aliases: ["Ash", "Ashley Williams"] },
    { name: "Nancy Wheeler", aliases: ["Nancy"] },
    { name: "Steve Harrington", aliases: ["Steve"] },
    { name: "Yui Kimura", aliases: ["Yui"] },
    { name: "Zarina Kassir", aliases: ["Zarina"] },
    { name: "Cheryl Mason", aliases: ["Cheryl", "Heather", "Heather Mason"] },
    { name: "Felix Richter", aliases: ["Felix"] },
    { name: "Élodie Rakoto", aliases: ["Elodie", "Élodie"] },
    { name: "Yun-Jin Lee", aliases: ["Yun-Jin", "Yunjin"] },
    { name: "Jill Valentine", aliases: ["Jill"] },
    { name: "Leon S. Kennedy", aliases: ["Leon", "Leon Kennedy", "Leon Scott Kennedy"] },
    { name: "Mikaela Reid", aliases: ["Mikaela"] },
    { name: "Jonah Vasquez", aliases: ["Jonah"] },
    { name: "Yoichi Asakawa", aliases: ["Yoichi"] },
    { name: "Haddie Kaur", aliases: ["Haddie"] },
    { name: "Ada Wong", aliases: ["Ada"] },
    { name: "Rebecca Chambers", aliases: ["Rebecca"] },
    { name: "Vittorio Toscano", aliases: ["Vittorio"] },
    { name: "Thalita Lyra", aliases: ["Thalita"] },
    { name: "Renato Lyra", aliases: ["Renato"] },
    { name: "Gabriel Soma", aliases: ["Gabriel", "Soma"] },
    { name: "Nicolas Cage", aliases: ["Cage", "Nic Cage", "Nick Cage"] },
    { name: "Ellen Ripley", aliases: ["Ripley", "Ellen"] },
    { name: "Alan Wake", aliases: ["Alan"] },
    { name: "Sable Ward", aliases: ["Sable"] },
    { name: "Aestri Yazar", aliases: ["Aestri", "Baermar Uraz", "Baermar", "The Troupe"] },
    { name: "Lara Croft", aliases: ["Lara", "Tomb Raider"] },
    { name: "Trevor Belmont", aliases: ["Trevor", "Belmont"] },
    { name: "Taurie Cain", aliases: ["Taurie"] },
    { name: "Sydney Prescott", aliases: ["Sydney", "Sidney", "Sidney Prescott"] },
    { name: "Rick Grimes", aliases: ["Rick"] },
    { name: "Michonne Grimes", aliases: ["Michonne"] },
    { name: "Vee Boonyasak", aliases: ["Vee"] }
  ],
  killers: [
    { name: "Trapper", aliases: ["Caçador"], portrait: "https://deadbydaylight.wiki.gg/images/K01_TheTrapper_Portrait.png" },
    { name: "Wraith", aliases: ["Espectro"], portrait: "https://deadbydaylight.wiki.gg/images/K02_TheWraith_Portrait.png" },
    { name: "Hillbilly", aliases: ["Billy", "Caipira"], portrait: "https://deadbydaylight.wiki.gg/images/K03_TheHillbilly_Portrait.png" },
    { name: "Nurse", aliases: ["Enfermeira"], portrait: "https://deadbydaylight.wiki.gg/images/K04_TheNurse_Portrait.png" },
    { name: "Shape", aliases: ["Michael Myers", "Forma"], portrait: "https://deadbydaylight.wiki.gg/images/K05_TheShape_Portrait.png" },
    { name: "Hag", aliases: ["Bruxa"], portrait: "https://deadbydaylight.wiki.gg/images/K06_TheHag_Portrait.png" },
    { name: "Doctor", aliases: ["Médico"], portrait: "https://deadbydaylight.wiki.gg/images/K07_TheDoctor_Portrait.png" },
    { name: "Huntress", aliases: ["Caçadora"], portrait: "https://deadbydaylight.wiki.gg/images/K08_TheHuntress_Portrait.png" },
    { name: "Cannibal", aliases: ["Bubba Sawyer", "Bubba", "Leatherface", "Canibal"], portrait: "https://deadbydaylight.wiki.gg/images/K09_TheCannibal_Portrait.png" },
    { name: "Nightmare", aliases: ["Freddy", "Pesadelo"], portrait: "https://deadbydaylight.wiki.gg/images/K10_TheNightmare_Portrait.png" },
    { name: "Pig", aliases: ["Porca"], portrait: "https://deadbydaylight.wiki.gg/images/K11_ThePig_Portrait.png" },
    { name: "Clown", aliases: ["Palhaço"], portrait: "https://deadbydaylight.wiki.gg/images/K12_TheClown_Portrait.png" },
    { name: "Spirit", aliases: ["Espírito"], portrait: "https://deadbydaylight.wiki.gg/images/K13_TheSpirit_Portrait.png" },
    { name: "Legion", aliases: ["Legião"], portrait: "https://deadbydaylight.wiki.gg/images/K14_TheLegion_Portrait.png" },
    { name: "Plague", aliases: ["Praga"], portrait: "https://deadbydaylight.wiki.gg/images/K15_ThePlague_Portrait.png" },
    { name: "Ghost Face", aliases: [], portrait: "https://deadbydaylight.wiki.gg/images/K16_TheGhostFace_Portrait.png" },
    { name: "Demogorgon", aliases: ["Demo"], portrait: "https://deadbydaylight.wiki.gg/images/K17_TheDemogorgon_Portrait.png" },
    { name: "Oni", aliases: [], portrait: "https://deadbydaylight.wiki.gg/images/K18_TheOni_Portrait.png" },
    { name: "Deathslinger", aliases: ["Pistoleiro"], portrait: "https://deadbydaylight.wiki.gg/images/K19_TheDeathslinger_Portrait.png" },
    { name: "Pyramid Head", aliases: ["Executioner", "Pirâmide", "O Carrasco"], portrait: "https://deadbydaylight.wiki.gg/images/K20_TheExecutioner_Portrait.png" },
    { name: "Blight", aliases: ["Ferrugem"], portrait: "https://deadbydaylight.wiki.gg/images/K21_TheBlight_Portrait.png" },
    { name: "Twins", aliases: ["Gêmeos"], portrait: "https://deadbydaylight.wiki.gg/images/K22_TheTwins_Portrait.png" },
    { name: "Trickster", aliases: ["Trapaceiro"], portrait: "https://deadbydaylight.wiki.gg/images/K23_TheTrickster_Portrait.png" },
    { name: "Nemesis", aliases: [], portrait: "https://deadbydaylight.wiki.gg/images/K24_TheNemesis_Portrait.png" },
    { name: "Cenobite", aliases: ["Cenobita"], portrait: "https://deadbydaylight.wiki.gg/images/K25_TheCenobite_Portrait.png" },
    { name: "Artist", aliases: ["Artista"], portrait: "https://deadbydaylight.wiki.gg/images/K26_TheArtist_Portrait.png" },
    { name: "Onryō", aliases: ["Sadako", "Samara"], portrait: "https://deadbydaylight.wiki.gg/images/K27_TheOnryo_Portrait.png" },
    { name: "Dredge", aliases: ["Draga"], portrait: "https://deadbydaylight.wiki.gg/images/K28_TheDredge_Portrait.png" },
    { name: "Mastermind", aliases: ["Wesker", "Mentor"], portrait: "https://deadbydaylight.wiki.gg/images/K29_TheMastermind_Portrait.png" },
    { name: "Knight", aliases: ["Cavaleiro"], portrait: "https://deadbydaylight.wiki.gg/images/K30_TheKnight_Portrait.png" },
    { name: "Skull Merchant", aliases: ["Adriana", "A Mercadora de Crânios"], portrait: "https://deadbydaylight.wiki.gg/images/K31_TheSkullMerchant_Portrait.png" },
    { name: "Singularity", aliases: ["Singularidade"], portrait: "https://deadbydaylight.wiki.gg/images/K32_TheSingularity_Portrait.png" },
    { name: "Xenomorph", aliases: ["Alien", "Xenomorfo"], portrait: "https://deadbydaylight.wiki.gg/images/K33_TheXenomorph_Portrait.png" },
    { name: "Good Guy", aliases: ["Chucky", "Boneco Assassino"], portrait: "https://deadbydaylight.wiki.gg/images/K34_TheGoodGuy_Portrait.png" },
    { name: "Unknown", aliases: ["Desconhecido", "Cido"], portrait: "https://deadbydaylight.wiki.gg/images/K35_TheUnknown_Portrait.png" },
    { name: "Lich", aliases: ["Vecna"], portrait: "https://deadbydaylight.wiki.gg/images/K36_TheLich_Portrait.png" },
    { name: "Dark Lord", aliases: ["Dracula", "O Lorde das Trevas"], portrait: "https://deadbydaylight.wiki.gg/images/K37_TheDarkLord_Portrait.png" },
    { name: "Houndmaster", aliases: ["Mestra dos Cães"], portrait: "https://deadbydaylight.wiki.gg/images/K38_TheHoundmaster_Portrait.png" },
    { name: "Ghoul", aliases: ["Kaneki", "Carniçal"], portrait: "https://deadbydaylight.wiki.gg/images/K39_TheGhoul_Portrait.png" },
    { name: "Animatronic", aliases: ["Freddy Fazbear", "FNAF", "Animatrônico"], portrait: "https://deadbydaylight.wiki.gg/images/K40_TheAnimatronic_Portrait.png" },
    { name: "Krasue", aliases: ["Senhora Linguiça"], portrait: "https://deadbydaylight.wiki.gg/images/K41_TheKrasue_Portrait.png" }
  ]
};
