const CHARACTERS = {
  survivors: [
    { name: 'Dwight Fairfield', aliases: [] },
    { name: 'Meg Thomas', aliases: [] },
    { name: 'Claudette Morel', aliases: [] },
    { name: 'Jake Park', aliases: [] },
    { name: 'Nea Karlsson', aliases: [] },
    { name: 'Laurie Strode', aliases: [] },
    { name: 'Ace Visconti', aliases: [] },
    { name: 'William Bill Overbeck', aliases: ['Velho'] },
    { name: 'Feng Min', aliases: [] },
    { name: 'David King', aliases: [] },
    { name: 'Quentin Smith', aliases: [] },
    { name: 'David Tapp', aliases: [] },
    { name: 'Kate Denson', aliases: [] },
    { name: 'Adam Francis', aliases: [] },
    { name: 'Jeff Johansen', aliases: [] },
    { name: 'Jane Romero', aliases: [] },
    { name: 'Ash Williams', aliases: [] },
    { name: 'Nancy Wheeler', aliases: [] },
    { name: 'Steve Harrington', aliases: [] },
    { name: 'Yui Kimura', aliases: [] },
    { name: 'Zarina Kassir', aliases: [] },
    { name: 'Cheryl Mason', aliases: [] },
    { name: 'Felix Richter', aliases: [] },
    { name: 'Élodie Rakoto', aliases: [] },
    { name: 'Yun-Jin Lee', aliases: [] },
    { name: 'Jill Valentine', aliases: [] },
    { name: 'Leon S. Kennedy', aliases: [] },
    { name: 'Mikaela Reid', aliases: [] },
    { name: 'Jonah Vasquez', aliases: [] },
    { name: 'Yoichi Asakawa', aliases: [] },
    { name: 'Haddie Kaur', aliases: [] },
    { name: 'Ada Wong', aliases: [] },
    { name: 'Rebecca Chambers', aliases: [] },
    { name: 'Vittorio Toscano', aliases: [] },
    { name: 'Thalita Lyra', aliases: [] },
    { name: 'Renato Lyra', aliases: [] },
    { name: 'Gabriel Soma', aliases: [] },
    { name: 'Nicolas Cage', aliases: [] },
    { name: 'Ellen Ripley', aliases: [] },
    { name: 'Alan Wake', aliases: [] },
    { name: 'Sable Ward', aliases: [] },
    { name: 'Aestri Yazar', aliases: [] },
    { name: 'Lara Croft', aliases: [] },
    { name: 'Trevor Belmont', aliases: [] },
    { name: 'Taurie Cain', aliases: [] },
    { name: 'Rick Grimes', aliases: [] },
    { name: 'Michonne Grimes', aliases: [] },
    { name: 'Vee Boonyasak', aliases: [] },
    { name: 'Dustin Henderson', aliases: [] },
    { name: 'Eleven', aliases: ['Jane Hopper', 'Onze', 'On', 'El'] },
  ],
  killers: [
    { name: 'Trapper', aliases: ['Caçador'] },
    { name: 'Wraith', aliases: ['Espectro'] },
    { name: 'Hillbilly', aliases: ['Billy', 'Caipira'] },
    { name: 'Nurse', aliases: ['Enfermeira'] },
    { name: 'Shape', aliases: ['Michael Myers', 'Forma'] },
    { name: 'Hag', aliases: ['Bruxa'] },
    { name: 'Doctor', aliases: ['Médico'] },
    { name: 'Huntress', aliases: ['Caçadora'] },
    { name: 'Cannibal', aliases: ['Bubba Sawyer', 'Bubba', 'Leatherface', 'Canibal'] },
    { name: 'Nightmare', aliases: ['Freddy', 'Pesadelo'] },
    { name: 'Pig', aliases: ['Porca'] },
    { name: 'Clown', aliases: ['Palhaço'] },
    { name: 'Spirit', aliases: ['Espírito'] },
    { name: 'Legion', aliases: ['Legião'] },
    { name: 'Plague', aliases: ['Praga'] },
    { name: 'Ghost Face', aliases: [] },
    { name: 'Demogorgon', aliases: ['Demo'] },
    { name: 'Oni', aliases: [] },
    { name: 'Deathslinger', aliases: ['Pistoleiro'] },
    { name: 'Pyramid Head', aliases: ['Executioner', 'Pirâmide', 'O Carrasco'] },
    { name: 'Blight', aliases: ['Ferrugem'] },
    { name: 'Twins', aliases: ['Gêmeos'] },
    { name: 'Trickster', aliases: ['Trapaceiro'] },
    { name: 'Nemesis', aliases: [] },
    { name: 'Cenobite', aliases: ['Cenobita'] },
    { name: 'Artist', aliases: ['Artista'] },
    { name: 'Onryō', aliases: ['Sadako', 'Samara'] },
    { name: 'Dredge', aliases: ['Draga'] },
    { name: 'Mastermind', aliases: ['Wesker', 'Mentor'] },
    { name: 'Knight', aliases: ['Cavaleiro'] },
    { name: 'Skull Merchant', aliases: ['Adriana', 'A Mercadora de Crânios'] },
    { name: 'Singularity', aliases: ['Singularidade'] },
    { name: 'Xenomorph', aliases: ['Alien', 'Xenomorfo'] },
    { name: 'Good Guy', aliases: ['Chucky', 'Boneco Assassino'] },
    { name: 'Unknown', aliases: ['Desconhecido', 'Cido'] },
    { name: 'Lich', aliases: ['Vecna'] },
    { name: 'Dark Lord', aliases: ['Dracula', 'O Lorde das Trevas'] },
    { name: 'Houndmaster', aliases: ['Mestra dos Cães'] },
    { name: 'Ghoul', aliases: ['Kaneki', 'Carniçal'] },
    { name: 'Animatronic', aliases: ['Freddy Fazbear', 'FNAF', 'Animatrônico'] },
    { name: 'Krasue', aliases: ['Senhora Linguiça'] },
    { name: 'The First', aliases: ['First', 'Vecna', 'One', 'Número Um', 'Henry Creel'] },
  ],
};

export const DEFAULT_CHARACTERS = {
  survivors: CHARACTERS.survivors.map((c) => [c.name, ...c.aliases].join('/')),
  killers: CHARACTERS.killers.map((c) => [c.name, ...c.aliases].join('/')),
};
